version: '3.7'

services:
  postgres:
    image: postgres:14.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ja_JP.UTF-8'
      TZ: Asia/Tokyo
    volumes:
      - postgres_volume:/var/lib/postgresql
      - ./postgresql/init:/docker-entrypoint-initdb.d
    hostname: postgres
  backend:
    tty: true
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     # - "1234:1234"
      - 8080:8080
    #  - "26162:26162"
    volumes:
      - .:/app4
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0 -p 8080"

volumes:
  postgres_volume:
    driver: local